# Extracción y construcción del dataset académico

Este notebook procesa fichas de rendimiento académico en formato PDF y genera un conjunto estructurado de registros académicos para análisis de trayectorias.

In [1]:
from pathlib import Path
import re
import pandas as pd

from pypdf import PdfReader

print("Entorno listo")

Entorno listo

In [2]:
BASE_DIR = Path("../")

DATA_RAW = BASE_DIR / "data" / "raw" / "pdf_estudiantes"

DATA_INTERIM = BASE_DIR / "data" / "interim"

print(DATA_RAW)

..\data\raw\pdf_estudiantes

In [3]:
def leer_pdf(ruta_pdf):
    
    reader = PdfReader(ruta_pdf)

    texto = ""

    for pagina in reader.pages:
        contenido = pagina.extract_text()

        if contenido:
            texto += contenido + "\n"

    return texto

In [4]:
archivos = list(DATA_RAW.glob("*.pdf"))

print(
    f"PDF encontrados: {len(archivos)}"
)

PDF encontrados: 247

In [5]:
def extraer_datos_generales(texto):

    datos = {}

    codigo = re.search(
        r"CÓDIGO / MATRÍCULA\s+(\d+)",
        texto
    )

    datos["id_estudiante"] = (
        codigo.group(1)
        if codigo else None
    )


    programa = re.search(
        r"PROGRAMA DE ESTUDIOS\s+(.*?)\s+APELLIDOS Y NOMBRES",
        texto,
        re.S
    )

    datos["programa_estudios"] = (
        programa.group(1).strip()
        if programa else None
    )

    return datos

In [6]:
def extraer_periodos(texto):

    patron = (
        r"Periodo Académico\s+Ciclo\s+"
        r"(\d{4}-[IV]+)\s+([IVX]+)"
    )

    return re.findall(
        patron,
        texto
    )

In [7]:
def evaluar_trayectoria(periodos):

    if len(periodos) >= 2:
        return "Incluido"

    return "Excluir"

In [8]:
def extraer_cursos(bloque, periodo, ciclo):

    cursos = []

    bloque = bloque.replace("\n", " ")
    bloque = re.sub(
        r"\s+",
        " ",
        bloque
    )

    patron = (
        r"\d+\s+(.*?)\s+"
        r"(PREVIO AL INICIO|LOGRADO|EN PROCESO|INICIO)"
        r"\s+(\d+)\s+(\d+)\s+(\d+)"
    )


    resultados = re.findall(
        patron,
        bloque
    )


    for curso, estado, nota, credito, puntaje in resultados:

        cursos.append({

            "periodo": periodo,
            "ciclo": ciclo,
            "curso": curso.strip(),
            "estado": estado,
            "nota": int(nota),
            "credito": int(credito),
            "puntaje": int(puntaje)

        })


    return cursos

In [9]:
def extraer_registros_academicos(texto):

    registros = []

    patron = (
        r"Periodo Académico\s+Ciclo\s+"
        r"(\d{4}-[IV]+)\s+([IVX]+)"
        r"(.*?)(?=Periodo Académico|$)"
    )


    periodos = re.findall(
        patron,
        texto,
        re.S
    )


    for periodo, ciclo, contenido in periodos:

        cursos = extraer_cursos(
            contenido,
            periodo,
            ciclo
        )

        registros.extend(cursos)


    return registros

In [10]:
def procesar_pdf(ruta_pdf):

    texto = leer_pdf(ruta_pdf)

    datos = extraer_datos_generales(texto)

    periodos = extraer_periodos(texto)


    if evaluar_trayectoria(periodos) == "Excluir":
        return [], {
            **datos,
            "cantidad_periodos": len(periodos),
            "decision": "Excluir"
        }


    registros = extraer_registros_academicos(texto)


    for registro in registros:
        registro.update(datos)


    resumen = {
        **datos,
        "cantidad_periodos": len(periodos),
        "decision": "Incluido"
    }


    return registros, resumen

In [11]:
todos_los_registros = []
resumen_estudiantes = []


for i, archivo in enumerate(archivos):

    print(
        f"Procesando {i+1}/{len(archivos)}: {archivo.name}"
    )


    registros, resumen = procesar_pdf(
        archivo
    )


    todos_los_registros.extend(
        registros
    )

    resumen_estudiantes.append(
        resumen
    )

Procesando 1/247: 04041859.pdf
Procesando 2/247: 10610527.pdf
Procesando 3/247: 20107537.pdf
Procesando 4/247: 20893955.pdf
Procesando 5/247: 21063279.pdf
Procesando 6/247: 21076480.pdf
Procesando 7/247: 21087602.pdf
Procesando 8/247: 21121175.pdf
Procesando 9/247: 21123566.pdf
Procesando 10/247: 21124788.pdf
Procesando 11/247: 21124939.pdf
Procesando 12/247: 21125146.pdf
Procesando 13/247: 21128581.pdf
Procesando 14/247: 21134535.pdf
Procesando 15/247: 21135881.pdf
Procesando 16/247: 21137050.pdf
Procesando 17/247: 21137674.pdf
Procesando 18/247: 21140269.pdf
Procesando 19/247: 40143017.pdf
Procesando 20/247: 40327272.pdf
Procesando 21/247: 40386407.pdf
Procesando 22/247: 40681363.pdf
Procesando 23/247: 40803998.pdf
Procesando 24/247: 41190593.pdf
Procesando 25/247: 42157445.pdf
Procesando 26/247: 42161435.pdf
Procesando 27/247: 42201929.pdf
Procesando 28/247: 42278910.pdf
Procesando 29/247: 42595681.pdf
Procesando 30/247: 42848467.pdf
Procesando 31/247: 42880150.pdf
Procesando 32/247: 42895135.pdf
Procesando 33/247: 42927916.pdf
Procesando 34/247: 43289149.pdf
Procesando 35/247: 43327558.pdf
Procesando 36/247: 43401748.pdf
Procesando 37/247: 43999922.pdf
Procesando 38/247: 44095515.pdf
Procesando 39/247: 44258340.pdf
Procesando 40/247: 44521820.pdf
Procesando 41/247: 44577385.pdf
Procesando 42/247: 44815462.pdf
Procesando 43/247: 45004109.pdf
Procesando 44/247: 45100179.pdf
Procesando 45/247: 45506034.pdf
Procesando 46/247: 45528157.pdf
Procesando 47/247: 45590241.pdf
Procesando 48/247: 45715886.pdf
Procesando 49/247: 45904093.pdf
Procesando 50/247: 45913871.pdf
Procesando 51/247: 46253955.pdf
Procesando 52/247: 46329075.pdf
Procesando 53/247: 46521245.pdf
Procesando 54/247: 46546831.pdf
Procesando 55/247: 46581278.pdf
Procesando 56/247: 46642802.pdf
Procesando 57/247: 46662454.pdf
Procesando 58/247: 46665583.pdf
Procesando 59/247: 46684318.pdf
Procesando 60/247: 46717128.pdf
Procesando 61/247: 46826831.pdf
Procesando 62/247: 46832540.pdf
Procesando 63/247: 46981507.pdf
Procesando 64/247: 46993357.pdf
Procesando 65/247: 47449679.pdf
Procesando 66/247: 47545090.pdf
Procesando 67/247: 47664115.pdf
Procesando 68/247: 47843072.pdf
Procesando 69/247: 47992634.pdf
Procesando 70/247: 48034152.pdf
Procesando 71/247: 48053589.pdf
Procesando 72/247: 48093627.pdf
Procesando 73/247: 48106311.pdf
Procesando 74/247: 48260628.pdf
Procesando 75/247: 48295779.pdf
Procesando 76/247: 48341657.pdf
Procesando 77/247: 60010952.pdf
Procesando 78/247: 60011012.pdf
Procesando 79/247: 60012389.pdf
Procesando 80/247: 60104833.pdf
Procesando 81/247: 60105020.pdf
Procesando 82/247: 60108703.pdf
Procesando 83/247: 60296771.pdf
Procesando 84/247: 60391835.pdf
Procesando 85/247: 60409631.pdf
Procesando 86/247: 60432665.pdf
Procesando 87/247: 60454717.pdf
Procesando 88/247: 60456788.pdf
Procesando 89/247: 60470475.pdf
Procesando 90/247: 60842214.pdf
Procesando 91/247: 60910818.pdf
Procesando 92/247: 60910993.pdf
Procesando 93/247: 61054240.pdf
Procesando 94/247: 61054391.pdf
Procesando 95/247: 61116001.pdf
Procesando 96/247: 61190261.pdf
Procesando 97/247: 61190278.pdf
Procesando 98/247: 61627051.pdf
Procesando 99/247: 62029539.pdf
Procesando 100/247: 62609237.pdf
Procesando 101/247: 62828478.pdf
Procesando 102/247: 70084051.pdf
Procesando 103/247: 70085353.pdf
Procesando 104/247: 70178621.pdf
Procesando 105/247: 70181326.pdf
Procesando 106/247: 70185734.pdf
Procesando 107/247: 70186703.pdf
Procesando 108/247: 70206447.pdf
Procesando 109/247: 70216011.pdf
Procesando 110/247: 70233631.pdf
Procesando 111/247: 70234815.pdf
Procesando 112/247: 70237784.pdf
Procesando 113/247: 70237868.pdf
Procesando 114/247: 70237881.pdf
Procesando 115/247: 70239478.pdf
Procesando 116/247: 70239503.pdf
Procesando 117/247: 70239517.pdf
Procesando 118/247: 70259346.pdf
Procesando 119/247: 70322000.pdf
Procesando 120/247: 70499324.pdf
Procesando 121/247: 70950082.pdf
Procesando 122/247: 71333121.pdf
Procesando 123/247: 71407236.pdf
Procesando 124/247: 71431071.pdf
Procesando 125/247: 71452496.pdf
Procesando 126/247: 71452504.pdf
Procesando 127/247: 71477667.pdf
Procesando 128/247: 71569770.pdf
Procesando 129/247: 71615352.pdf
Procesando 130/247: 71704121.pdf
Procesando 131/247: 71707331.pdf
Procesando 132/247: 71738175.pdf
Procesando 133/247: 71828745.pdf
Procesando 134/247: 71850794.pdf
Procesando 135/247: 71999608.pdf
Procesando 136/247: 72044120.pdf
Procesando 137/247: 72073664.pdf
Procesando 138/247: 72074201.pdf
Procesando 139/247: 72076492.pdf
Procesando 140/247: 72077064.pdf
Procesando 141/247: 72077110.pdf
Procesando 142/247: 72077113.pdf
Procesando 143/247: 72080902.pdf
Procesando 144/247: 72089236.pdf
Procesando 145/247: 72089259.pdf
Procesando 146/247: 72089261.pdf
Procesando 147/247: 72091938.pdf
Procesando 148/247: 72095592.pdf
Procesando 149/247: 72102707.pdf
Procesando 150/247: 72176582.pdf
Procesando 151/247: 72236749.pdf
Procesando 152/247: 72250717.pdf
Procesando 153/247: 72254001.pdf
Procesando 154/247: 72484930.pdf
Procesando 155/247: 72603966.pdf
Procesando 156/247: 72611344.pdf
Procesando 157/247: 72611617.pdf
Procesando 158/247: 72635989.pdf
Procesando 159/247: 72890738.pdf
Procesando 160/247: 73068757.pdf
Procesando 161/247: 73145516.pdf
Procesando 162/247: 73183248.pdf
Procesando 163/247: 73329236.pdf
Procesando 164/247: 73331669.pdf
Procesando 165/247: 73414019.pdf
Procesando 166/247: 73450468.pdf
Procesando 167/247: 73542019.pdf
Procesando 168/247: 73596737.pdf
Procesando 169/247: 73618723.pdf
Procesando 170/247: 73618724.pdf
Procesando 171/247: 73674279.pdf
Procesando 172/247: 73684680.pdf
Procesando 173/247: 73869355.pdf
Procesando 174/247: 73905166.pdf
Procesando 175/247: 74041450.pdf
Procesando 176/247: 74143852.pdf
Procesando 177/247: 74236099.pdf
Procesando 178/247: 74283141.pdf
Procesando 179/247: 74318543.pdf
Procesando 180/247: 74354231.pdf
Procesando 181/247: 74365850.pdf
Procesando 182/247: 74367959.pdf
Procesando 183/247: 74471643.pdf
Procesando 184/247: 74810920.pdf
Procesando 185/247: 74817028.pdf
Procesando 186/247: 74841547.pdf
Procesando 187/247: 74925127.pdf
Procesando 188/247: 74950002.pdf
Procesando 189/247: 75006422.pdf
Procesando 190/247: 75066092.pdf
Procesando 191/247: 75066130.pdf
Procesando 192/247: 75085721.pdf
Procesando 193/247: 75185462.pdf
Procesando 194/247: 75192960.pdf
Procesando 195/247: 75198346.pdf
Procesando 196/247: 75213633.pdf
Procesando 197/247: 75213634.pdf
Procesando 198/247: 75225462.pdf
Procesando 199/247: 75225479.pdf
Procesando 200/247: 75225538.pdf
Procesando 201/247: 75236666.pdf
Procesando 202/247: 75275491.pdf
Procesando 203/247: 75315093.pdf
Procesando 204/247: 75464088.pdf
Procesando 205/247: 75486708.pdf
Procesando 206/247: 75551659.pdf
Procesando 207/247: 75551660.pdf
Procesando 208/247: 75551670.pdf
Procesando 209/247: 75581890.pdf
Procesando 210/247: 75627008.pdf
Procesando 211/247: 75660617.pdf
Procesando 212/247: 75660643.pdf
Procesando 213/247: 75682644.pdf
Procesando 214/247: 75685290.pdf
Procesando 215/247: 75697099.pdf
Procesando 216/247: 75705812.pdf
Procesando 217/247: 75722182.pdf
Procesando 218/247: 75728496.pdf
Procesando 219/247: 75731310.pdf
Procesando 220/247: 75772515.pdf
Procesando 221/247: 75789592.pdf
Procesando 222/247: 75793680.pdf
Procesando 223/247: 75793704.pdf
Procesando 224/247: 75822066.pdf
Procesando 225/247: 75867546.pdf
Procesando 226/247: 75933912.pdf
Procesando 227/247: 76020497.pdf
Procesando 228/247: 76020588.pdf
Procesando 229/247: 76021164.pdf
Procesando 230/247: 76026971.pdf
Procesando 231/247: 76072019.pdf
Procesando 232/247: 76166327.pdf
Procesando 233/247: 76195574.pdf
Procesando 234/247: 76612067.pdf
Procesando 235/247: 76687175.pdf
Procesando 236/247: 76732921.pdf
Procesando 237/247: 76785417.pdf
Procesando 238/247: 76791479.pdf
Procesando 239/247: 76826760.pdf
Procesando 240/247: 76831448.pdf
Procesando 241/247: 76848698.pdf
Procesando 242/247: 76943877.pdf
Procesando 243/247: 77340606.pdf
Procesando 244/247: 77346260.pdf
Procesando 245/247: 77356554.pdf
Procesando 246/247: 77492003.pdf
Procesando 247/247: 78547538.pdf

In [12]:
df_registros = pd.DataFrame(
    todos_los_registros
)

df_registros.head()

,periodo,ciclo,curso,estado,nota,credito,puntaje,id_estudiante,programa_estudios
0,2024-I,I,DESARROLLO PERSONAL I,LOGRADO,15,3,45,04041859,EDUCACIÓN PRIMARIA (R.V.M N° 204 - 2019 - MINEDU)
1,2024-I,I,DESARROLLO Y APRENDIZAJE I,EN PROCESO,13,5,65,04041859,EDUCACIÓN PRIMARIA (R.V.M N° 204 - 2019 - MINEDU)
2,2024-I,I,FUNDAMENTOS PARA LA EDUCACIÓN PRIMARIA,LOGRADO,15,5,75,04041859,EDUCACIÓN PRIMARIA (R.V.M N° 204 - 2019 - MINEDU)
3,2024-I,I,LECTURA Y ESCRITURA EN LA EDUCACIÓN SUPERIOR,LOGRADO,15,3,45,04041859,EDUCACIÓN PRIMARIA (R.V.M N° 204 - 2019 - MINEDU)
4,2024-I,I,PRÁCTICA E INVESTIGACIÓN I,EN PROCESO,13,5,65,04041859,EDUCACIÓN PRIMARIA (R.V.M N° 204 - 2019 - MINEDU)

In [13]:
df_resumen = pd.DataFrame(
    resumen_estudiantes
)

df_resumen.head()

,id_estudiante,programa_estudios,cantidad_periodos,decision
0,04041859,EDUCACIÓN PRIMARIA (R.V.M N° 204 - 2019 - MINEDU),5,Incluido
1,10610527,COMPUTACIÓN E INFORMÁTICA (R.D. N° 0223 - 2012...,5,Incluido
2,20107537,EDUCACIÓN PRIMARIA (R.V.M N° 204 - 2019 - MINEDU),5,Incluido
3,20893955,COMUNICACIÓN (R.V.M N° 143 - 2020 - MINEDU),2,Incluido
4,21063279,EDUCACIÓN FÍSICA (R.V.M N° 147 - 2020 - MINEDU),8,Incluido

In [14]:
df_registros.to_csv(
    DATA_INTERIM / "registros_academicos_raw.csv",
    index=False,
    encoding="utf-8-sig"
)


df_resumen.to_csv(
    DATA_INTERIM / "resumen_estudiantes.csv",
    index=False,
    encoding="utf-8-sig"
)